
package org.eclipse.stardust.engine.api.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-01-09T10:24:12.225+01:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "bpmFault", targetNamespace = "http://eclipse.org/stardust/ws/v2012a/api")
public class BpmFault extends Exception {
    
    private org.eclipse.stardust.engine.api.ws.BpmFaultXto bpmFault;

    public BpmFault() {
        super();
    }
    
    public BpmFault(String message) {
        super(message);
    }
    
    public BpmFault(String message, Throwable cause) {
        super(message, cause);
    }

    public BpmFault(String message, org.eclipse.stardust.engine.api.ws.BpmFaultXto bpmFault) {
        super(message);
        this.bpmFault = bpmFault;
    }

    public BpmFault(String message, org.eclipse.stardust.engine.api.ws.BpmFaultXto bpmFault, Throwable cause) {
        super(message, cause);
        this.bpmFault = bpmFault;
    }

    public org.eclipse.stardust.engine.api.ws.BpmFaultXto getFaultInfo() {
        return this.bpmFault;
    }
}
