//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.05 at 12:11:22 PM CEST 
//


package org.eclipse.stardust.engine.extensions.jaxws.addressing.infinity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infinity.bpm.rt.integration.webservices.addressing.carnot package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ID_QNAME = new QName("http://www.w3.org/2006/02/addressing/wsdl", "ID");
    private final static QName _OID_QNAME = new QName("http://www.w3.org/2006/02/addressing/wsdl", "OID");
    private final static QName _VALUE_QNAME = new QName("http://www.w3.org/2006/02/addressing/wsdl", "VALUE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infinity.addressing.carnot
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfinityValueExtensionType }
     * 
     */
    public InfinityValueExtensionType createInfinityValueExtensionType() {
        return new InfinityValueExtensionType();
    }

    /**
     * Create an instance of {@link InfinityIdExtensionType }
     * 
     */
    public InfinityIdExtensionType createInfinityIdExtensionType() {
        return new InfinityIdExtensionType();
    }

    /**
     * Create an instance of {@link InfinityOidExtensionType }
     * 
     */
    public InfinityOidExtensionType createInfinityOidExtensionType() {
        return new InfinityOidExtensionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfinityIdExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/02/addressing/wsdl", name = "ID")
    public JAXBElement<InfinityIdExtensionType> createID(InfinityIdExtensionType value) {
        return new JAXBElement<InfinityIdExtensionType>(_ID_QNAME, InfinityIdExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfinityOidExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/02/addressing/wsdl", name = "OID")
    public JAXBElement<InfinityOidExtensionType> createOID(InfinityOidExtensionType value) {
        return new JAXBElement<InfinityOidExtensionType>(_OID_QNAME, InfinityOidExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfinityValueExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/02/addressing/wsdl", name = "VALUE")
    public JAXBElement<InfinityValueExtensionType> createVALUE(InfinityValueExtensionType value) {
        return new JAXBElement<InfinityValueExtensionType>(_VALUE_QNAME, InfinityValueExtensionType.class, null, value);
    }

}
