//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.05 at 11:30:22 AM CEST 
//

@XmlSchema(
      xmlns = {
            @XmlNs(namespaceURI = ObjectFactory.NAMESPACE, prefix = ObjectFactory.PREFIX)
      },
      namespace = ObjectFactory.NAMESPACE,
      elementFormDefault = XmlNsForm.QUALIFIED)
package org.eclipse.stardust.engine.extensions.jaxws.addressing.wsdl;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
